name: "my workflow"
on: push
# some comment
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "John"

      - name: Setup Xamarin
        uses: maxim-lobanov/setup-xamarin@v1
        
